name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--line-length 101"
      - uses: isort/isort-action@v1
        with:
          configuration: "--check-only --diff --profile black"
